/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Concessionaria;


/**
 *
 * @author Guilherme
 */
public class Aplicacao extends javax.swing.JFrame {

    private final Concessionaria concessionaria;
    private final TelaCliente telacliente;
    private final TelaFuncionario telafuncionario;
    private final TelaVeiculo telaveiculo;
    private final TelaVenda telavenda;
    private final TelaRelatorio telarelatorio;


    /**
     * Creates new form Interface
     */
    public Aplicacao() {
        initComponents();
        this.concessionaria = new Concessionaria();
        this.telacliente = new TelaCliente(this.concessionaria);
        this.telafuncionario = new TelaFuncionario(this.concessionaria);
        this.telaveiculo = new TelaVeiculo(this.concessionaria);
        this.telavenda = new TelaVenda(this.concessionaria);
        this.telarelatorio = new TelaRelatorio(this.concessionaria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonGC = new javax.swing.JButton();
        jButtonGF = new javax.swing.JButton();
        jButtonGVei = new javax.swing.JButton();
        jButtonGVen = new javax.swing.JButton();
        jButtonGR = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciamento Concessionaria");

        jButtonGC.setText("Gerenciamento de Clientes");
        jButtonGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciamentoClienteButtonActionPerformed(evt);
            }
        });

        jButtonGF.setText("Gerenciamento de Funcionarios");
        jButtonGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciamentoFuncionarioButtonActionPerformed(evt);
            }
        });

        jButtonGVei.setText("Gerenciamento de Veiculos");
        jButtonGVei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciamentoVeiculoButtonActionPerformed(evt);
            }
        });

        jButtonGVen.setText("Gerenciamento de Venda");
        jButtonGVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerencimentoVeiculoButtonActionPerformed(evt);
            }
        });

        jButtonGR.setText("Gerenciamento de Relatorio");
        jButtonGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerencimentoRelatorioButtonActionPerformed(evt);
            }
        });

        jButton6.setText("Sair do Programa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonGF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGVei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGVen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jButtonGC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGVei)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGVen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GerenciamentoClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciamentoClienteButtonActionPerformed
        this.jButtonGC.setVisible(true);
    }//GEN-LAST:event_GerenciamentoClienteButtonActionPerformed

    private void GerenciamentoFuncionarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciamentoFuncionarioButtonActionPerformed
        this.jButtonGF.setVisible(true);
    }//GEN-LAST:event_GerenciamentoFuncionarioButtonActionPerformed

    private void GerenciamentoVeiculoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciamentoVeiculoButtonActionPerformed
        this.jButtonGVei.setVisible(true);
    }//GEN-LAST:event_GerenciamentoVeiculoButtonActionPerformed

    private void GerencimentoVeiculoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerencimentoVeiculoButtonActionPerformed
        this.jButtonGVen.setVisible(true);
    }//GEN-LAST:event_GerencimentoVeiculoButtonActionPerformed

    private void GerencimentoRelatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerencimentoRelatorioButtonActionPerformed
        this.jButtonGR.setVisible(true);
    }//GEN-LAST:event_GerencimentoRelatorioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonGC;
    private javax.swing.JButton jButtonGF;
    private javax.swing.JButton jButtonGR;
    private javax.swing.JButton jButtonGVei;
    private javax.swing.JButton jButtonGVen;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
