/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Concessionaria;
import javax.swing.JFrame;

/**
 *
 * @author Guilherme
 */
public class TelaRelatorio extends javax.swing.JFrame {

    private final Concessionaria concessionaria;
    private final TelaRelatorioCliente relatoriocliente;
    private final TelaRelatorioFuncionario relatoriofuncionario;
    private final TelaRelatorioVeiculo relatorioveiculo;
    private final TelaRelatorioVenda relatoriovenda;

    /**
     * Creates new form Relatorio
     */
    public TelaRelatorio(Concessionaria concessionaria) {
        initComponents();
        this.concessionaria = concessionaria;
        this.relatoriocliente = new TelaRelatorioCliente(this.concessionaria);
        this.relatoriofuncionario = new TelaRelatorioFuncionario(this.concessionaria);
        this.relatorioveiculo = new TelaRelatorioVeiculo(this.concessionaria);
        this.relatoriovenda = new TelaRelatorioVenda(this.concessionaria);
        setTitle("Menu Relatorio");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Menu Relatorios");

        jButton27.setText("Relatorio de clientes");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioClienteButtonActionPerformed(evt);
            }
        });

        jButton28.setText("Relatorio de funcionarios");
        jButton28.setToolTipText("");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioFuncionarioButtonActionPerformed(evt);
            }
        });

        jButton29.setText("Relatorio de veiculos");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioVeiculoButtonActionPerformed(evt);
            }
        });

        jButton30.setText("Relatorio de vendas");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioVendaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addComponent(jButton27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton30)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RelatorioClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioClienteButtonActionPerformed
        this.relatoriocliente.setVisible(true);
    }//GEN-LAST:event_RelatorioClienteButtonActionPerformed

    private void RelatorioFuncionarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioFuncionarioButtonActionPerformed
        this.relatoriofuncionario.setVisible(true);
    }//GEN-LAST:event_RelatorioFuncionarioButtonActionPerformed

    private void RelatorioVeiculoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioVeiculoButtonActionPerformed
        this.relatorioveiculo.setVisible(true);
    }//GEN-LAST:event_RelatorioVeiculoButtonActionPerformed

    private void RelatorioVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioVendaButtonActionPerformed
        this.relatoriovenda.setVisible(true);
    }//GEN-LAST:event_RelatorioVendaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
