/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Concessionaria;
import java.util.ArrayList;
import javax.swing.JFrame;
import model.Cliente;

/**
 *
 * @author Guilherme
 */
public class TelaCliente extends javax.swing.JFrame {
    
    private final Concessionaria concessionaria;
    private final TelaClienteCadastrar clientecadastrar;
    private final TelaClienteConsultar clienteconsultar;
    private final TelaClienteAlterar clientealterar;
    private final TelaClienteRemover clienteremover;
            
    /**
     * Creates new form Cliente
     * @param concessionaria
     * @param clientes
     */
    public TelaCliente(Concessionaria concessionaria) {
        initComponents();
        this.concessionaria = concessionaria;
        this.clientecadastrar = new TelaClienteCadastrar(this.concessionaria);
        this.clienteconsultar = new TelaClienteConsultar(this.concessionaria);
        this.clientealterar = new TelaClienteAlterar(this.concessionaria);
        this.clienteremover = new TelaClienteRemover(this.concessionaria);
        setTitle("Menu Clientes");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Menu Clientes");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonCadastrar.setText("Cadastrar cliente");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteButtonActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("Consultar cliente");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarClienteButtonActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar cliente");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarClienteButtonActionPerformed(evt);
            }
        });

        jButtonRemover.setText("Remover cliente");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverClienteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(jButtonCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemover)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteButtonActionPerformed
        this.clientecadastrar.setVisible(true);
    }//GEN-LAST:event_CadastrarClienteButtonActionPerformed

    private void ConsultarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarClienteButtonActionPerformed
        this.clienteconsultar.setVisible(true);
    }//GEN-LAST:event_ConsultarClienteButtonActionPerformed

    private void AlterarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarClienteButtonActionPerformed
        this.clientealterar.setVisible(true);
    }//GEN-LAST:event_AlterarClienteButtonActionPerformed

    private void RemoverClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverClienteButtonActionPerformed
        this.clienteremover.setVisible(true);
    }//GEN-LAST:event_RemoverClienteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
