/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Concessionaria;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import model.Venda;

/**
 *
 * @author Guilherme
 */
public class TelaRelatorioVenda extends javax.swing.JFrame {
    private final Concessionaria controller;
    /**
     * Creates new form Relatorio
     * @param controller
     */
    public TelaRelatorioVenda(Concessionaria controller) {
        initComponents();
        this.controller = controller;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Relatorio Venda");
        relatorioVenda();
    }
    
    public void relatorioVenda() {
        ArrayList<Venda> listaVendas = controller.consultarVenda();
        DefaultListModel<String> model = new DefaultListModel<>();

        if (listaVendas.isEmpty()) {
            model.addElement("Nenhum Venda cadastrada.");
        } 
        else {
            for (Venda venda : listaVendas) {
                String cpfCliente = (venda.getCliente() != null) ? venda.getCliente().getCpf() : "N/A";
                String matriculaFuncionario = (venda.getFuncionario() != null) ? venda.getFuncionario().getNum_matricula() : "N/A";
                String idVeiculo = (venda.getVeiculo() != null) ? venda.getVeiculo().getId() : "N/A";
                
                String item = "Data: " + venda.getData()+
                            " | Valor: " + venda.getValor()+
                            " | CPF do cliente: " + cpfCliente+
                            " | Numero de matricula funcionario: " + matriculaFuncionario+ 
                            " | Identificador do veiculo: " + idVeiculo+
                            " | Identificador da venda: " + venda.getId();
                model.addElement(item);
            }
        }
        jListRelatorio.setModel(model);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane12 = new javax.swing.JScrollPane();
        jListRelatorio = new javax.swing.JList<>();
        jLabel68 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListRelatorio.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(jListRelatorio);

        jLabel68.setText("Relatorio vendas");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBuscar)
                    .addComponent(jLabel68))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel68)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarButtonActionPerformed
        relatorioVenda();
    }//GEN-LAST:event_BuscarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JList<String> jListRelatorio;
    private javax.swing.JScrollPane jScrollPane12;
    // End of variables declaration//GEN-END:variables
}
